spring:
  application:
    name: focusguard

  datasource:
    url: jdbc:postgresql://localhost:5432/focusguarddb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
